// <auto-generated />
using System;
using Fuse8.BackendInternship.PublicApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fuse8.BackendInternship.PublicApi.Migrations
{
    [DbContext(typeof(UsersDBContext))]
    [Migration("20250413151855_v1.0")]
    partial class v10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fuse8.BackendInternship.PublicApi.Models.FavoriteRateDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseCurrencyType")
                        .HasColumnType("integer")
                        .HasColumnName("base_currency_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SelectedCurrencyType")
                        .HasColumnType("integer")
                        .HasColumnName("selected_currency_type");

                    b.HasKey("Id")
                        .HasName("pk_favorite_exchanges");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_favorite_exchanges_name");

                    b.HasIndex("SelectedCurrencyType", "BaseCurrencyType")
                        .IsUnique()
                        .HasDatabaseName("ix_favorite_exchanges_selected_currency_type_base_currency_type");

                    b.ToTable("favorite_exchanges", "user");
                });
#pragma warning restore 612, 618
        }
    }
}
